name: speech_to_text_macos
publish_to: none
description: macOS implementation of the speech_to_text plugin
repository: https://github.com/csdcorp/speech_to_text/speech_to_text_macos
issue_tracker: https://github.com/csdcorp/speech_to_text/issues
version: 1.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  # speech_to_text_platform_interface: ^2.0.1
  speech_to_text_platform_interface:
    # path: ../speech_to_text_platform_interface
    git:
      url: https://github.com/lh900519/speech_to_text.git
      path: speech_to_text_platform_interface
      ref: feat_aec

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    implements: speech_to_text
    platforms:
      macos:
        pluginClass: SpeechToTextMacosPlugin
        dartPluginClass: SpeechToTextMacOS
